[package]
name = "main"
version = "0.1.0"
authors = ["raaz4n"]
edition = "2024"
description = "Testing this bot using Rust."

[dependencies]
dotenv = "0.15.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
poise = "0.6.1"

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "chrono",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.12"
