[package]
name = "main"
version = "0.1.0"
authors = ["raaz4n"]
edition = "2024"
description = "Testing this bot using Rust."

[dependencies]
dotenv = "0.15"
tokio = { version = "1.21.2", features = ["full"] }
poise = "0.6.1"
serde = "1.0.228"
serde_json = "1.0.149"
reqwest = { version = "0.12", features = ["json"] }
config = "0.13"
quick-xml = { version = "0.39.2", features = ["serialize"] }

[dependencies.serenity]
default-features = false
features = [
    "builder",
    "chrono",
    "client",
    "framework",
    "gateway",
    "http",
    "model",
    "standard_framework",
    "utils",
    "rustls_backend",
]
version = "0.12"
